package vn.dnse.openapi.websocket.codec;

import com.fasterxml.jackson.databind.JsonNode;
import org.junit.jupiter.api.Test;
import vn.dnse.openapi.websocket.dispatcher.MessageMapper;
import vn.dnse.openapi.websocket.model.Trade;

import java.math.BigDecimal;
import java.util.Base64;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;

class MessagePackPythonFixtureTest {

    // Generated by Python msgpack.packb(...) using the same payload shape as dnse.websocket.encoding.MessageEncoder.
    private static final String PYTHON_TRADE_FIXTURE =
            "jqFUoXSobWFya2V0SWSkSE9TRadib2FyZElkokcxpGlzaW6sVk4wMDAwMDBGUFQxpnN5bWJvbKNGUFSqbWF0Y2hQcmljZctAXtzMzMzMzaltYXRjaFF0dHlksXRvdGFsVm9sdW1lVHJhZGVkzROIsGdyb3NzVHJhZGVBbW91bnTLQSLWRAAAAACsaGlnaGVzdFByaWNly0BfQAAAAAAAq2xvd2VzdFByaWNly0BeAAAAAAAAqW9wZW5QcmljZctAXkAAAAAAALB0cmFkaW5nU2Vzc2lvbklkAaR0aW1lzmaFHgA=";

    @Test
    void decodesPythonGeneratedMessagePackFixture() {
        MessagePackCodec codec = new MessagePackCodec();
        JsonNode node = codec.decode(Base64.getDecoder().decode(PYTHON_TRADE_FIXTURE));

        Trade trade = assertInstanceOf(Trade.class, MessageMapper.map(node, 123L));
        assertEquals("FPT", trade.symbol());
        assertEquals(new BigDecimal("123.45"), trade.price());
        assertEquals(100L, trade.quantity());
        assertEquals("trade", MessageMapper.eventName(node));
    }
}
